# Generated by Django 4.2.9 on 2024-01-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='items',
            field=models.ManyToManyField(related_name='menus', to='accounts.item'),
        ),
    ]
