# Generated by Django 4.2.9 on 2024-01-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_menu_items_restaurant_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='items',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menus',
        ),
    ]
