# Generated by Django 4.2.9 on 2024-01-27 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_restaurant_items_remove_restaurant_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='accounts.item'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='accounts.menu'),
        ),
    ]
